import React from 'react';
import { Play, Gamepad2, Zap, Sliders } from 'lucide-react';
import { sound } from '../services/soundEngine';

const quickGames = [['fruit_catch','🍎','Fruit Catch','Guide the basket with your hand and catch the falling fruit.'],['balloon_pop','🎈','Balloon Pop','Reach out to burst balloons before they drift away.'],['star_collector','★','Star Collector','Touch every star before the timer runs out.'],['freeze_move','🧊','Freeze & Move','Move on green, and hold perfectly still on red.']];
export default function Home({ onSelectGame, setActiveTab, sensitivity, onCycleSensitivity }) {
  const play = (id) => { sound.playClick(); onSelectGame(id); };
  return <div className="app-container">
    <section className="hero-section"><div><div className="eyebrow">Webcam motion games</div><h1 className="hero-title">Get up.<br/><em>Play differently.</em></h1><p className="hero-subtitle">MotionPlay turns your camera into a simple game controller. Use your hands, lean, jump, and move—no keyboard needed.</p><div className="hero-actions"><button className="btn-primary" onClick={() => play('motion_runner')}><Play size={17} fill="currentColor"/> Start Motion Runner</button><button className="btn-secondary" onClick={() => { sound.playClick(); setActiveTab('games'); }}><Gamepad2 size={17}/> Browse games</button></div></div><aside className="hero-note"><strong>Before you begin</strong>Give yourself a little room, face the camera, and check that your whole body is visible for pose-controlled games.</aside></section>
    <section className="setting-strip"><div className="setting-strip-icon"><Zap size={19}/></div><div><h4>Motion sensitivity: {sensitivity}</h4><p>Try a lower setting if the camera picks up small movements too easily.</p></div><button className="btn-secondary" onClick={onCycleSensitivity}><Sliders size={16}/> Adjust setting</button></section>
    <section className="featured-card"><div className="featured-content"><div className="featured-badge">Recommended today</div><h3>Motion Runner</h3><p>A three-lane run powered by your body. Lean to change lanes, jump over obstacles, and crouch under signs.</p><button className="btn-primary" onClick={() => play('motion_runner')}><Zap size={17}/> Play Motion Runner</button></div><div className="featured-visual"><div className="runner">🏃</div><span>FULL BODY · 3 LANES · LIVE TRACKING</span></div></section>
    <section><div className="section-heading"><h2>Pick a game</h2><p>Short, movement-led games designed to get you comfortable with camera controls.</p></div><div className="games-grid">{quickGames.map(([id,icon,title,description]) => <article key={id} className="game-card" onClick={() => play(id)} style={{cursor:'pointer'}}><div className="game-icon">{icon}</div><h3 className="game-title">{title}</h3><p className="game-desc">{description}</p><button className="btn-secondary">Play game <span aria-hidden="true">→</span></button></article>)}</div></section>
  </div>;
}
